### ISSUE TITLE
app won't start

### ISSUE THREAD

**Issue by FayeKaneGirlBrain** [ari-zah/gaiasky#13]
**I installed jre1.8.0_40 and rebooted. I moved the gia sandbox files and folders to the directory containing java.exe.  When I execute run.bat under win7/64 I get:**

java -Dproperties.file=conf/global.properties -jar gaiasandbox.jar

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/badlogic/gdx/ApplicationListener
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.privateGetMethodRecursive(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.badlogic.gdx.ApplicationListener
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        7 more

**One would not expect this to run anyway, as Windows uses the backslash as a directory delimiter, not slash. That alone indicates a serious misconfiguration in run.bat. But changing it to slash makes no difference.**

**Running just the first half of the command line**
java -Dproperties.file=conf/global.properties
**makes java give me a help screen, as if I ran java.exe with no parameters at all.** 

**Moving the file "global.properties" up to the current directory and running:**
java -Dproperties.file=global.properties
**yields the same result. The -D is ignored.**

**Running just the second half of the command line**
java -jar gaiasandbox.jar
**gives the procedure traceback error message described above.  Yes,  gaiasandbox.jar is in the current directory.**

**Why?**

**-faye kane**

**Comment by langurmonkey** [comment]
I can not replicate this, it works well for me in Windows 7. It seems that the libraries are not being loaded. Can you confirm that the `lib` folder is in the same directory as the `gaiasandbox.jar` and the `run.bat`, and that you are executing the `run.bat` from this same directory?

**Comment by langurmonkey** [comment]
Closed due to inactivity
