### ISSUE TITLE
New Version 1.0.0 doesn`t work on OSX 10.10.5

### ISSUE THREAD

**Issue by Skydiver2k16** [ari-zah/gaiasky#75]
Hi Folks,
everytime ill start the app an error occured that writes the following in the log File.

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at java.util.Calendar.setTime(Calendar.java:1770)
	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:943)
	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:936)
	at java.text.DateFormat.format(DateFormat.java:345)
	at gaia.cu9.ari.gaiaorbit.desktop.format.DesktopDateFormat.format(DesktopDateFormat.java:27)
	at gaia.cu9.ari.gaiaorbit.desktop.util.DesktopConfInit.persistGlobalConf(DesktopConfInit.java:327)
	at gaia.cu9.ari.gaiaorbit.desktop.gui.swing.ConfigDialog$16.actionPerformed(ConfigDialog.java:984)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

I don`t know what it means, perhaps you guys have an solution for this problem.

Thanks and regards,
Skydiver2k16

**Comment by langurmonkey** [comment]
Can you try deleting the file `$HOME/.gaiasky/global.properties` and running the program again?

**Comment by langurmonkey** [comment]
Thanks for reporting! I can confirm this is a bug which occurs when you try to run the Gaia Sky for the first time without being connected to the internet. It has been fixed in the development branch but the fix won't make it into the main release until next version.
As a temporary workaround, you can edit the file `$HOME/.gaiasky/global.properties` and change the line that reads

```
program.lastchecked=
```
into
```
program.lastchecked=19/09/2016 09\:30\:01
```
Let me know if this works for you.

**Comment by Skydiver2k16** [comment]
Hey Langurmonkey,
thanks for the information that this is truly is a bug. ;-)
I ve tested your workaround but i must say that it doesn t work for me.

I have 2 row where the part `program.lastchecked=` exist.

If i change the row 
`# Last time checked for new version
program.lastchecked=`
nothing happened and everything works (NOT) as before.

If i change the row
`# Last version checked
program.lastchecked=`
the program brokes directly down. :-(

**Comment by langurmonkey** [comment]
If a line starts with a hash symbol `#` it means that it is a comment, so you should put the `program.lastchecked=19/09/2016 09\:30\:01` into a new line.

**Comment by Skydiver2k16** [comment]
Sorry the editor here has omitted the break ;)

 Just want to show u the line when it breaks directly.
Correctly it should seen like this:

If i change the rows
`# Last time checked for new version`
`program.lastchecked=` 
nothing happened and everything works (NOT) as before.

If i change the rows
`# Last version checked`
`program.lastchecked=`
the program brokes directly down. :-(

**Comment by langurmonkey** [comment]
But did you add the **date** to the right of the equal sign? I don't see it in your lines.
```
# Last version checked
program.lastchecked=19/09/2016 09\:30\:01
```

**Comment by Skydiver2k16** [comment]
Yes i did.

**Comment by langurmonkey** [comment]
Hmm, weird. So after changing the line there is no log message whatsoever?

I am attaching a zip file which contains a `gaiasky.jar` file with the bugfix. Replace the `[GAIASKY_INSTALL_FOLDER]/lib/gaiasky.jar` with this one and the issue should be fixed.

[gaiasky.zip](https://github.com/ari-zah/gaiasky/files/479534/gaiasky.zip)

**Comment by Skydiver2k16** [comment]
I`ve just replaced the gaiasky.jar file. After that the program does`t start.
I see the Icon for a second and then it closes directly.
Here is the Logfile after that crash.

`java.util.MissingResourceException: Can't find bundle key element.360
	at com.badlogic.gdx.utils.I18NBundle.get(I18NBundle.java:436)
	at gaia.cu9.ari.gaiaorbit.interfce.KeyBindings.txt(KeyBindings.java:397)
	at gaia.cu9.ari.gaiaorbit.interfce.KeyBindings.initDefault(KeyBindings.java:248)
	at gaia.cu9.ari.gaiaorbit.interfce.KeyBindings.<init>(KeyBindings.java:46)
	at gaia.cu9.ari.gaiaorbit.interfce.KeyBindings.initialize(KeyBindings.java:31)
	at gaia.cu9.ari.gaiaorbit.desktop.GaiaSkyDesktop.main(GaiaSkyDesktop.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:65)
	at com.install4j.runtime.launcher.MacLauncher.main(MacLauncher.java:67)`

**Comment by langurmonkey** [comment]
Oh, yes, of course, replace the files in `[GAIASKY_INSTALL_FOLDER]/i18n/` with the ones in the attached zip. Sorry about that ;)

[i18n.zip](https://github.com/ari-zah/gaiasky/files/479630/i18n.zip)

**Comment by Skydiver2k16** [comment]
Don t worry about. The new file "works" so that i can see the start screen again, ... but.
The App already won t start. :-(
Here is the new Error.log

`Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:459)
	at java.util.Properties.setProperty(Properties.java:166)
	at gaia.cu9.ari.gaiaorbit.desktop.util.DesktopConfInit.persistGlobalConf(DesktopConfInit.java:328)
	at gaia.cu9.ari.gaiaorbit.desktop.gui.swing.ConfigDialog$16.actionPerformed(ConfigDialog.java:984)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by langurmonkey** [comment]
I'm not even sure what is going on anymore, these null pointer exceptions should not be happening.
Let's try this last jar file, maybe we're lucky.

[gaiasky.zip](https://github.com/ari-zah/gaiasky/files/479661/gaiasky.zip)

**Comment by Skydiver2k16** [comment]
Hey Langurmonkey, you are the men!

IT WORKS :-)

Thank you very much!

**Comment by langurmonkey** [comment]
Great! I'll close the bug then. Enjoy ;)
